name: vital_bloom
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dartz: ^0.10.1
  dio: ^5.4.2
  easy_context: ^1.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  get_it: ^7.6.7
  google_sign_in: ^6.2.1
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pretty_dio_logger: ^1.3.1

flutter:
  uses-material-design: true
