name: vital_bloom
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  dartz: ^0.10.1
  dio: ^5.4.2
  easy_context: ^1.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  get_it: ^7.6.7
  google_sign_in: ^6.2.1
  health: ^9.0.1
  lazy_load_indexed_stack: ^1.1.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  syncfusion_flutter_gauges: ^25.1.37
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pretty_dio_logger: ^1.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/navigation/

    